language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Vjp1Lhqmwy+rKEX1DWZ0mnA2R2bdSCXhuldKO8pr/eO0KgrcHMrWhjLVo1lThYGD/YC/K+TmhpZKUx7RY3pIp9mInXmSPVj4kn8UWxDz3+bXMIA80XW4oZt2JRoOsCn2K9EGe6uVE/p7R8ZEALUypeTQUaarMBV2dfywPkfbbgf/uZhF/L80Vk4iko0iIoUa+gDu3P8+h0mCZp/LAMh83ptus9EV6anOoWQnSlpfKDySWA1ptW0vUC5cJJ9r+Vx+SZuz4JGT2shnEI0aKfBAlZAL+kQA6F0XC5cQllBRVcMNzRZ8LOS54Q1mHuvfzGyaQPx/kv3yeLLUylmMty8/NBj+5GWQmcD0Hv71FB4fxH7S9kVOL+lEeTxjK0pbzwHSymbH0QOPzXmbR5CipNvpUvN21/zDocKrilHYLZWeXTVnUodrom0C2PZwdvrJ0bQfZ5oM5rJyaYqxfodXNkIr7pMtBh4JRefxoER0KVkISY+qyptQpcP6rzqjAANgXXNVbU0ey6oizmiDFWmwIo7wywbNogAChx8o9e4lV4CBfRbUnfeA7myt29r7LxhjkUgDS2Zj9BKrNs7elOyurWYTrbEzHADeeSBczIC5F/TZah0D4M/Jq0It8HMPlLO4+fCe9pquJrv+z5HAUBH6T3To9P0+E26T92vNRQAdpYqVIBk=
  app: node-restaurants-app-mongoose
  on:
    repo: jkathan/node-restaurants-app-mongoose
    branch: feature/with-tests
